### ISSUE TITLE
The client is broken- Unable to Install

### ISSUE THREAD

**Issue by saviour123** [infobip/infobip-api-python-client#10]
When i run 
`pip install `

I got this response
```sh
Collecting infobip-api-python-client
  Using cached infobip-api-python-client-2.2.0.tar.gz (32 kB)
Collecting enum
  Using cached enum-0.4.7.tar.gz (20 kB)
    ERROR: Command errored out with exit status 1:
     command: /Users/saviourgidi/projects/python_extensive/total/total/env/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/vf/rl30wcj92_g723bs9nskxns80000gn/T/pip-install-qduaoqvr/enum/setup.py'"'"'; __file__='"'"'/private/var/folders/vf/rl30wcj92_g723bs9nskxns80000gn/T/pip-install-qduaoqvr/enum/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/vf/rl30wcj92_g723bs9nskxns80000gn/T/pip-pip-egg-info-k7agivbt
         cwd: /private/var/folders/vf/rl30wcj92_g723bs9nskxns80000gn/T/pip-install-qduaoqvr/enum/
    Complete output (11 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/Users/saviourgidi/projects/python_extensive/total/total-backend/env/lib/python3.7/site-packages/setuptools/__init__.py", line 6, in <module>
        import distutils.core
      File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/distutils/core.py", line 16, in <module>
        from distutils.dist import Distribution
      File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/distutils/dist.py", line 9, in <module>
        import re
      File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/re.py", line 143, in <module>
        class RegexFlag(enum.IntFlag):
    AttributeError: module 'enum' has no attribute 'IntFlag'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.```

**Comment by shubh12et1062** [comment]
Is this library supported on python3.6 yet ?

**Comment by kiselica-aldin** [comment]
Hello @saviour123 

as you might have noticed, we recently formed a DevRel initiative.

Why is this relevant are 2 things:
- we are working on a new release of the library `3.0.0` (which should land during Q2) and support Python versions `>= 3.6`
- we are not onboarded nor we support older lib versions -> we tackle all of them one by one and start supporting them from the version we release.

I understand that this does not resolve the issue you opened, it does not even tell you how to fix it. It simply serves as an announcement that we are working on something new and that we will be fully responsive to that.
